### ISSUE TITLE
No results found on debug application

### ISSUE THREAD

**Issue by 0xfisherman** [assetnote/kiterunner#27]
Hello
First of all congrats for amazing tool.

Problem: Currently i can't see the request output. only the following information is printed during and after scan:

```
INF no results found/s) [3s:1h20m50s]
Continue Scanning with full wordlist? [y/n]: y
INF scan complete duration=13311.47994 results=0 
```

Expected: GET STATUS-CODE [] URL ID
Command: kr scan http://localhost:8080/ -w wordlist/routes-small.kite

Can be related with configs?
Thanks

**Comment by minight** [comment]
This will only return non-wildcard results found with the specified wordlist. if you have an application that just returns the same thing for every route, then no results will be found.
The current output indicates that no unique results were found (all results were wildcarded, or otherwise). If you want to disable this, set `--wildcard-detection=false`.

**Comment by 0xfisherman** [comment]
In the point.

Many Thanks
